import { Link } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/ip-notice")({
  component: IPNotice,
});

function IPNotice() {
  return (
    <div className="min-h-screen bg-background px-4 pb-32 pt-6">
      <Link to="/settings" className="mb-6 flex items-center gap-2 text-sm text-muted-foreground">
        <ArrowLeft className="size-4" /> Back to Settings
      </Link>

      <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Legal</p>
      <h1 className="font-serif text-3xl italic mt-1 mb-1">IP & Copyright Notice</h1>
      <p className="text-sm text-muted-foreground mb-8">Effective date: June 2025</p>

      <div className="space-y-8 text-sm leading-relaxed text-foreground">

        <section>
          <h2 className="font-semibold text-base mb-2">1. Original Content</h2>
          <p>All explainer articles, news summaries, interface design, branding, and original written content produced by CivicIntel are protected by copyright under the <strong>Copyright Act (Kenya), Cap 130</strong>. Unauthorised reproduction, distribution, or commercial use of this content is prohibited.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">2. News Attribution</h2>
          <p>CivicIntel summarises publicly available news from third-party sources. We always attribute the original publisher and provide a link to the full article. We do not reproduce full articles verbatim. Our summarisation practice is consistent with fair dealing provisions under Kenyan copyright law for purposes of reporting current events and education.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">3. AI-Generated Content</h2>
          <p>Responses generated by CivicIntel AI are produced dynamically in response to user queries. They are educational in nature and do not reproduce copyrighted works. AI responses do not represent legal opinions and should not be relied upon as such.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">4. Kenyan Government Documents</h2>
          <p>The Constitution of Kenya 2010, Acts of Parliament, Kenya Gazette notices, Hansard records, and other official government publications are public documents. CivicIntel may quote, reference, or summarise them under public interest and educational use provisions. Such references do not imply affiliation with or endorsement by the Government of Kenya.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">5. Third-Party Trademarks</h2>
          <p>References to government bodies and institutions — including the National Assembly, Senate, National Treasury, Central Bank of Kenya (CBK), Kenya Revenue Authority (KRA), Huduma Kenya, NHIF, NSSF, and county governments — are made for identification and educational purposes only. CivicIntel is not affiliated with, sponsored by, or endorsed by any of these bodies.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">6. Photography Credits</h2>
          <p>Building and civic photography used in the app is sourced from Wikimedia Commons under Creative Commons or public domain licences:</p>
          <ul className="space-y-2 list-disc pl-4 mt-2">
            <li>Parliament Buildings, Nairobi — Jorge Láscar, CC BY-SA 2.0</li>
            <li>Nairobi City Hall — Jorge Láscar, CC BY-SA 2.0</li>
            <li>Supreme Court of Kenya — Francis Akuka / Wikimedia Foundation, CC0</li>
            <li>Central Bank of Kenya — Sidhanta Khuntia, CC BY-SA 4.0</li>
            <li>Times Tower, Nairobi (Kenya Revenue Authority) — Ruslik0, CC BY-SA 4.0</li>
            <li>Ballot box — Smithsonian Institution, public domain</li>
          </ul>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">7. Copyright Takedown / DMCA</h2>
          <p>If you believe that content on CivicIntel infringes your copyright, please contact us with the following information:</p>
          <ul className="space-y-2 list-disc pl-4 mt-2">
            <li>A description of the copyrighted work you believe has been infringed.</li>
            <li>The specific URL or location of the allegedly infringing content on CivicIntel.</li>
            <li>Your full name and contact information.</li>
            <li>A statement that you have a good-faith belief that the use is not authorised.</li>
          </ul>
          <p className="mt-2">Send takedown requests to: <strong>civicintel.ke@gmail.com</strong>. We will respond within 14 business days.</p>
        </section>

        <section>
          <h2 className="font-semibold text-base mb-2">8. Contact</h2>
          <p>Email: <strong>civicintel.ke@gmail.com</strong></p>
          <p className="mt-1">Nairobi, Kenya</p>
        </section>

      </div>
    </div>
  );
}
