/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepresentativesRouteImport } from './routes/representatives'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'

const RepresentativesRoute = RepresentativesRouteImport.update({
  id: '/representatives',
  path: '/representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/glossary': typeof GlossaryRoute
  '/learn': typeof LearnRouteWithChildren
  '/posts': typeof PostsRoute
  '/reels': typeof ReelsRoute
  '/representatives': typeof RepresentativesRoute
  '/learn/$slug': typeof LearnSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/glossary': typeof GlossaryRoute
  '/learn': typeof LearnRouteWithChildren
  '/posts': typeof PostsRoute
  '/reels': typeof ReelsRoute
  '/representatives': typeof RepresentativesRoute
  '/learn/$slug': typeof LearnSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/glossary': typeof GlossaryRoute
  '/learn': typeof LearnRouteWithChildren
  '/posts': typeof PostsRoute
  '/reels': typeof ReelsRoute
  '/representatives': typeof RepresentativesRoute
  '/learn/$slug': typeof LearnSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/glossary'
    | '/learn'
    | '/posts'
    | '/reels'
    | '/representatives'
    | '/learn/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/glossary'
    | '/learn'
    | '/posts'
    | '/reels'
    | '/representatives'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/glossary'
    | '/learn'
    | '/posts'
    | '/reels'
    | '/representatives'
    | '/learn/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  GlossaryRoute: typeof GlossaryRoute
  LearnRoute: typeof LearnRouteWithChildren
  PostsRoute: typeof PostsRoute
  ReelsRoute: typeof ReelsRoute
  RepresentativesRoute: typeof RepresentativesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/representatives': {
      id: '/representatives'
      path: '/representatives'
      fullPath: '/representatives'
      preLoaderRoute: typeof RepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  GlossaryRoute: GlossaryRoute,
  LearnRoute: LearnRouteWithChildren,
  PostsRoute: PostsRoute,
  ReelsRoute: ReelsRoute,
  RepresentativesRoute: RepresentativesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
